spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://redis:6379"
          database: 10
          connectionMinimumIdleSize: 12
        threads: 16
        nettyThreads: 32
        transportMode: "NIO"

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://mysql:3306/suiteboot-example?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: root
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      remove-abandoned: true
  data:
    mongodb:
      uri: mongodb://mongodb:27017/suiteboot-example?replicaSet=myReplicaSet
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

logging:
  config: classpath:logback.xml

oss:
  gridfs:
    enabled: true
    endpoint: http://192.168.2.5:8080

notify:
  enable: false
  mail:
    enable: false
  websocket:
    enable: true
  dingtalk:
    enable: false


suiteboot:
  script:
    path:
      sourceFile: ./expand/java
      classFile: ./expand/class
    loadingIgnore:
      ClientScript: false
      RecordEvent: true
      Restlet: false
      Schedule: true
      FlowEvent: true
      ButtonEvent: false
      ViewEvent: true
      BatchOperationEvent: false
      PowerJob: true

integration:
  enabled: false


powerjob:
  worker:
    enabled: false

